### ISSUE TITLE
刷新任一个新闻详情页，页面加载异常

### ISSUE THREAD

**Issue by Eamonnzhang** [biaodigit/vue-news#2]
刷新后为空白，应该是state的id没有传进去

**Comment by biaodigit** [comment]
很正常啊，因为vuex刷新后状态清空

**Comment by Eamonnzhang** [comment]
id = this.$store.state.id || this.$route.params.id，空的时候从路由上拿ID，然后去请求数据吧，这样用户体验好一点。

**Comment by biaodigit** [comment]
那这样做不如直接用路由id获取数据，vuex+localStorage才是最佳组合。说了这么多，给个star可好？
