### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by huanshili** [biaodigit/vue-news#3]
我想下载你的项目来学习，进行了如下操作：

1. git clone https://github.com/biaodigit/vue-news.git

2. npm install

3. npm run dev

报错，无法运行项目

**Comment by biaodigit** [comment]
stylus在npm 3.0以上需要先安装依赖再npm install

**Comment by biaodigit** [comment]
具体安装依赖操作：npm install stylus --save-dev

**Comment by huanshili** [comment]
好的，我试试哈，先谢谢啦！

**Comment by huanshili** [comment]
我之前好像是因为端口号的问题，后面修改端口号之后能跑出来了，但是页面有点问题：
![页面](https://cloud.githubusercontent.com/assets/16486174/25626176/40ee3d12-2f91-11e7-9974-ce7e79270f40.jpeg)

打开开发调试发现页面引用css 和js有问题

![wechatimg7](https://cloud.githubusercontent.com/assets/16486174/25628113/a4778856-2f97-11e7-85c3-b37efe7f7837.jpeg)
![wechatimg8](https://cloud.githubusercontent.com/assets/16486174/25628133/b7112fa8-2f97-11e7-8a9c-f29fdc00c1df.jpeg)
### 正常情况应该是这样的：
![wechatimg9](https://cloud.githubusercontent.com/assets/16486174/25628165/d2dc0cd0-2f97-11e7-8e1b-694b472f4b56.jpeg)

**Comment by biaodigit** [comment]
你从chrome看的是打包后的，并没有问题
